Try coverage tool

diff --git a/.github/workflows/test-unit.yml b/.github/workflows/test-unit.yml
--- a/.github/workflows/test-unit.yml
+++ b/.github/workflows/test-unit.yml
@@ -16,11 +16,12 @@ env:
   GO111MODULE: "on"
   RUN_BASE_COVERAGE: "on"  # Runs test for PR base in case base test coverage is missing.
   COV_GO_VERSION: 1.18.x   # Version of Go to collect coverage
+  TARGET_DELTA_COV: 90     # Target coverage of changed lines, in percents
 jobs:
   test:
     strategy:
       matrix:
-        go-version: [ 1.16.x, 1.17.x, 1.18.x, tip ]
+        go-version: [ 1.16.x, 1.17.x, 1.18.x ]
     runs-on: ubuntu-latest
     steps:
       - name: Install Go stable
@@ -76,19 +77,25 @@ jobs:
         run: |
           make test-unit
           go tool cover -func=./unit.coverprofile | sed -e 's/.go:[0-9]*:\t/.go\t/g' | sed -e 's/\t\t*/\t/g'  > unit.txt
-          OUTPUT=$(test -e unit-base.txt && (diff unit-base.txt unit.txt || exit 0) || cat unit.txt)
-          echo "${OUTPUT}"
-          OUTPUT="${OUTPUT//$'\n'/%0A}"
-          TOTAL=$(grep 'total:' unit.txt)
-          echo "${TOTAL}"
-          echo "::set-output name=diff::$OUTPUT"
+      - name: Annotate missing test coverage
+        id: annotate
+        if: matrix.go-version == env.COV_GO_VERSION && github.event.pull_request.base.sha != ''
+        run: |
+          git fetch origin master ${{ github.event.pull_request.base.sha }}
+          curl -sLO https://github.com/vearutop/gocovdiff/releases/download/v1.3.0/linux_amd64.tar.gz && tar xf linux_amd64.tar.gz && echo "c5fa13a6bce4e2c1960941f13e32429d8e05c909d4a08e41c46b83b72b162374  gocovdiff" | shasum -c
+          REP=$(./gocovdiff -cov unit.coverprofile -gha-annotations gha-unit.txt -delta-cov-file delta-cov-unit.txt -target-delta-cov ${TARGET_DELTA_COV})
+          echo "${REP}"
+          REP="${REP//$'\n'/%0A}"
+          cat gha-unit.txt
+          DIFF=$(test -e unit-base.txt && (gocovdiff -func-cov unit.txt -func-base-cov unit-base.txt) || echo "Missing base coverage file")
+          TOTAL=$(cat delta-cov-unit.txt)
+          echo "::set-output name=rep::$REP"
+          echo "::set-output name=diff::$DIFF"
           echo "::set-output name=total::$TOTAL"
-      - name: Store base coverage
-        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
-        run: cp unit.txt unit-base.txt
+
       - name: Comment Test Coverage
         continue-on-error: true
-        if: matrix.go-version == env.COV_GO_VERSION
+        if: matrix.go-version == env.COV_GO_VERSION && github.event.pull_request.base.sha != ''
         uses: marocchino/sticky-pull-request-comment@v2
         with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -96,12 +103,23 @@ jobs:
           message: |
             ### Unit Test Coverage
             ${{ steps.test.outputs.total }}
+            ${{ steps.annotate.outputs.total }}
+            <details><summary>Coverage of changed lines</summary>
+            
+            ${{ steps.annotate.outputs.rep }}
+
+            </details>
+
             <details><summary>Coverage diff with base branch</summary>
 
             ```diff
-            ${{ steps.test.outputs.diff }}
+            ${{ steps.annotate.outputs.diff }}
             ```
             </details>
+
+      - name: Store base coverage
+        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
+        run: cp unit.txt unit-base.txt
 
       - name: Upload code coverage
         if: matrix.go-version == env.COV_GO_VERSION
